#!/bin/bash

dir="$HOME/csgo_ds/csgo/addons/sourcemod"

if [[ ! -d "$dir/scripting/include/timer.inc" ]]; then
 cp -rf addons/sourcemod/scripting/include/* $dir/scripting/include/
fi

test -e compiled || mkdir compiled

for sourcefile in addons/sourcemod/scripting/*.sp
do
  smxfile="`echo $sourcefile | sed -e 's/\.sp$/\.smx/'`"
  echo -e "Compiling $sourcefile ..."
  $dir/scripting/spcomp $sourcefile -o$dir/plugins/${smxfile/addons\/sourcemod\/scripting\//}
  RETVAL=$?
  if [ $RETVAL -ne 0 ]; then
    exit 1;
  fi
done
