#!/bin/bash

server_dir="$HOME/csgo_ds/csgo"

# make addons folder
test -e $server_dir/addons || mkdir $server_dir/addons 

# sourcemod 
rm -rf $server_dir/sourcemod
cp -rf csgo/addons/sourcemod $server_dir/addons/sourcemod

# metamod 
rm -rf $server_dir/metamod
cp -rf csgo/addons/metamod $server_dir/addons/metamod

# metamod vdf file
cp csgo/addons/metamod.vdf $server_dir/addons/

# timer config
test -e $server_dir/cfg/sourcemod || mkdir $server_dir/cfg/sourcemod
cp -rf csgo/cfg/sourcemod/timer $server_dir/cfg/sourcemod/timer

# sound files
cp -rf csgo/sound/timer_sounds $server_dir/sound/timer_sounds

# server confguration files
cp csgo/* $server_dir
