#!/bin/bash

sm_server="$HOME/csgo_ds/csgo/addons/sourcemod"
sm_local="csgo/addons/sourcemod"

for sourcefile in $sm_local/scripting/timer/*.sp
do
  smxfile="`echo $sourcefile | sed -e 's/\.sp$/\.smx/'`"

  echo -e "Compiling $sourcefile into server plugin folder..."
  $sm_local/scripting/spcomp $sourcefile -o$sm_server/plugins/${smxfile/csgo\/addons\/sourcemod\/scripting\/timer\//}

  echo -e "Compiling $sourcefile into local plugin folder..."
  $sm_local/scripting/spcomp $sourcefile -o$sm_local/plugins/${smxfile/csgo\/addons\/sourcemod\/scripting\/timer\//}

  RETVAL=$?
  if [ $RETVAL -ne 0 ]; then
    exit 1;
  fi
done
