#!/bin/bash

server_dir="$HOME/csgo_ds/csgo"

# make addons folder
test -e $server_dir/addons || mkdir $server_dir/addons 

# sourcemod 
rm -rf $server_dir/addons/sourcemod
cp -rf csgo/addons/sourcemod $server_dir/addons/sourcemod

# metamod 
rm -rf $server_dir/addons/metamod
cp -rf csgo/addons/metamod $server_dir/addons/metamod

# metamod vdf file
cp -rf csgo/addons/metamod.vdf $server_dir/addons/

# cfg files 
cp -rf csgo/cfg/sourcemod $server_dir/cfg
cp -rf csgo/cfg/* $server_dir/cfg

# sound files
cp -rf csgo/sound/timer_sounds $server_dir/sound/timer_sounds
cp -rf csgo/sound/ui/* $server_dir/sound/ui
cp -rf csgo/sound/misc $server_dir/sound/misc

# map files
#find $server_dir/maps -maxdepth 1 -type f -delete
cp -f csgo/* $server_dir/
cp -rf csgo/maps/* $server_dir/maps
